export const SUPABASE_URL = process.env.SUPABASE_URL;
export const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;
export const WEB3FORMS_CONTACT_US_ACCESS_KEY =
  process.env.WEB3FORMS_CONTACT_US_ACCESS_KEY;
export const WEB3FORMS_NEW_ORDER_ACCESS_KEY =
  process.env.WEB3FORMS_NEW_ORDER_ACCESS_KEY;
